// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDToqYlzh-Y6BKHxqEhhgtdVO7ZAkQ84gw',
    appId: '1:682485604915:web:fb0a4f65d78a3739f37946',
    messagingSenderId: '682485604915',
    projectId: 'datt-eda89',
    authDomain: 'datt-eda89.firebaseapp.com',
    storageBucket: 'datt-eda89.firebasestorage.app',
    measurementId: 'G-NG8BMBKBKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZOS56mMlFvHXC9UfovUs6TqdrYoqEiw4',
    appId: '1:682485604915:android:288b3f1c529aa405f37946',
    messagingSenderId: '682485604915',
    projectId: 'datt-eda89',
    storageBucket: 'datt-eda89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ54NGpiZjNVQp8vPKc-Ld_1rrrhuIs4Q',
    appId: '1:682485604915:ios:1550a001ad29ab23f37946',
    messagingSenderId: '682485604915',
    projectId: 'datt-eda89',
    storageBucket: 'datt-eda89.firebasestorage.app',
    androidClientId: '682485604915-54qlpgqlp2v2brtlo5lct6jn2cgeaqrj.apps.googleusercontent.com',
    iosClientId: '682485604915-d49ikiglo1f67gr4bga6nvlvanpp57sm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ54NGpiZjNVQp8vPKc-Ld_1rrrhuIs4Q',
    appId: '1:682485604915:ios:1550a001ad29ab23f37946',
    messagingSenderId: '682485604915',
    projectId: 'datt-eda89',
    storageBucket: 'datt-eda89.firebasestorage.app',
    androidClientId: '682485604915-54qlpgqlp2v2brtlo5lct6jn2cgeaqrj.apps.googleusercontent.com',
    iosClientId: '682485604915-d49ikiglo1f67gr4bga6nvlvanpp57sm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDToqYlzh-Y6BKHxqEhhgtdVO7ZAkQ84gw',
    appId: '1:682485604915:web:89e6221724490167f37946',
    messagingSenderId: '682485604915',
    projectId: 'datt-eda89',
    authDomain: 'datt-eda89.firebaseapp.com',
    storageBucket: 'datt-eda89.firebasestorage.app',
    measurementId: 'G-DWBXCC36V0',
  );
}
